# Generated by Django 4.2.11 on 2024-04-17 18:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_date_of_birth_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[users.models.TodayDateValidator()],
                verbose_name="Дата рождения",
            ),
        ),
    ]
