# Generated by Django 4.2.11 on 2024-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="is_available",
            field=models.BooleanField(
                default=False, verbose_name="Доступен для выбора"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_displayed",
            field=models.BooleanField(
                default=False, verbose_name="Отображается в списке"
            ),
        ),
    ]
