# Generated by Django 4.2.11 on 2024-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_city_is_available_user_is_displayed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="e-mail"),
        ),
    ]
